"""Added Subscriber_claims table

Revision ID: bdf190afce5a
Revises: 
Create Date: 2023-07-05 23:31:28.579168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf190afce5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('submitted_procedure', sa.String(), nullable=False),
    sa.Column('quadrant', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('subscriber', sa.BigInteger(), nullable=False),
    sa.Column('provider_npi', sa.BigInteger(), nullable=False),
    sa.Column('provider_fees', sa.Float(), nullable=False),
    sa.Column('allowed_fees', sa.Float(), nullable=False),
    sa.Column('member_coinsurance', sa.Float(), nullable=False),
    sa.Column('member_copay', sa.Float(), nullable=False),
    sa.Column('net_fee', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber_claims')
    # ### end Alembic commands ###
